version: '3.8'

services:
  api:
    container_name: "${SPRING_APPLICATION_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_NAME: "${SPRING_APPLICATION_NAME}"
      SPRING_PORT: "${SPRING_PORT}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ${SPRING_PORT}:${SPRING_PORT}

  db:
    container_name: "${DB_HOST}"
    image: postgres:15
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    external: false
