version: '3'

services:
  api:
    container_name: "${SPRING_APPLICATION_NAME}"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SPRING_PORT}:${SPRING_PORT}"
    environment:
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      SPRING_PORT: "${SPRING_PORT}"
      SPRING_APPLICATION_NAME: "${SPRING_APPLICATION_NAME}"
    depends_on:
      - db
  db:
    container_name: "${DB_HOST}"
    image: postgres:15
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data: